//
//  game.swift
//  Charades2.0
//
//  Created by Rachel Ebert on 5/15/18.
//  Copyright © 2018 John Hersey High School. All rights reserved.
//

import Foundation

struct WhichArray {
    let AnimalWords =  ["Llama", "Dog", "Fly", "Parrot", "Sheep", "Coyote", "Lion", "Zebra", "Cheetah", "Polar Bear", "Bear", "Owl", "Tiger", "Husky", "Panda", "Monkey", "Penguin", "Peacock", "Fox", "Dolphin", "Deer", "Chicken", "Turkey", "Pig", "Fish", "Rhino", "Cow", "Frog", "Bunny", "Wolf", "Porcupine", "Whale", "Kangaroo", "Cat", "Horse", "Snake", "Dragon", "Clownfish", "African Buffalo", "Alpaca", "Baboon", "Aardvark", "African Bush Elephant", "Elephant", "Alligator", "Tortoise", "Water Spaniel", "Antelope", "Hare", "Rabbit", "Hornet", "Badger", "Camel", "Barracuda", "Basset Hound", "Beaver", "Bison", "Black Widow", "Buffalo", "Bulldog", "Butterfly", "Capybara", "Caterpillar", "Centipede", "Chameleon", "Chihuahua", "Chipmunk", "Cougar", "Crocodile", "Donkey", "Eel", "Emu", "Falcon", "Flat Coat Retriever", "Flying Squirrel", "Gecko", "Giant African Land Snail", "Honey Bee", "Seal", "Guppy", "Shark", "Mouse", "Iguana", "Jaguar", "Jellyfish", "Komodo Dragon", "Octopus", "Opossum", "Mongoose", "Platypus", "Raccoon", "Swan", "Walrus", "Wooly Mammoth"]
    
    let FamousPeople = ["Jay - Z", "Brad Pitt", "Katy Perry", "Benedict Cumberbatch", "Donald Trump", "Oprah", "Prince Harry", "Sandra Bullock", "Tom Hanks", "Chris Pratt", "Chris Evans", "Scarlett Johansson", "Tom Holland", "Josh Brolin",  "Robert Downey Jr", "Stan Lee", "Chris Hemsworth", "Vin Diesel", "Mark Ruffalo", "Ninja", "Angelina Jolie", "Kim Kardashian", "Natalie Portman", "Viola Davis", "Selena Gomez", "Amy Adams", "Alicia Keys", "Anne Hathaway", "Blake Lively", "Avril Lavigne", "Brooke Shield", "Celine Dion", "Christina Aguilera", "Corbin Bleu", "Courteney Cox", "Dakota Fanning", "Drew Barrymore", "Emma Roberts", "Ellen DeGeneres", "Emma Watson", "Fergie", "Gwen Stefani", "George Clooney", "Hugh Jackman", "Hilary Duff", "Heath Ledger", "Isla Fisher", "James Franco", "Janet Jackson", "Jennifer Lopez", "Jamie Lynn Spears", "Jessica Alba", "Joe Jonas", "John Krasinski", "Amy Pohler", "John Mayer", "Jordin Sparks", "Johnny Depp", "Jude Law", "Julia Roberts", "Josh Hutcherson", "Katie Holmes", "Kate Hudson", "Justin Timberlake", "Justin Beiber", "Keira Knightley", "Keith Urban", "Kellan Lutz", "Kelly Clarkson", "Kelly Ripa", "Kerry Washington", "Kirsten Dunst", "Kristen Stewart", "Lady Gaga", "Madonna", "Lea Michele", "Mandy Moore", "Mariah Carey", "Matt Damon", "Ed Sheeran"]
    
    let avengersWords = ["Captain America", "Falcon", "Ant-man", "Wasp", "Vision", "Scarlet Witch", "Hulk", "Thor", "Phil Coulson", "Bucky Barnes", "Spiderman", "Hawkeye", "Black Panther", "Wakanda", "Thanos", "Proxima Midnight", "The Ebony Maw", "Corvus Glaive", "Black Dwarf", "Loki", "Rocket", "Groot", "Star Lord", "Gamora","Drax", "Mantis", "Black Widow", "Ronan The Accuser", "Ego", "Deadpool", "Nebula", "Quicksilver", "Captain Marvel", "Daredevil", "War Machine", "Apocalypse"]
    
    let stateWords = ["Washington", "Montana", "North Dakota", "Minnesota", "Wisconsin", "Michigan", "Ohio", "Pennsylvania", "New York", "New Hampshire", "Maine", "Massachusetts", "Delaware", "Rhode Island", "Maryland", "Vermont", "New Jersey", "Connecitcut", "Virginia", "West Virginia", "North Carolina", "South Carolina", "Georgia", "Florida", "Alabama", "Mississippi", "Louisiana", "Texas", "New Mexico", "Arizona", "California", "Nevads", "Utah", "Colorado", "Kansas", "Missouri", "Illinois", "Indiana", "Kentucky", "Tennessee", "Oregon", "Wyoming", "South Dakota", "Oklahoma", "Arkansas", "Alaska", "Hawaii"]
    
    let throwback = ["Party in the USA", "Hollaback Girl", "Turn Up the Music", "All Star", "Beautiful Soul", "Your Love Is My Drug", "So What", "Sk8ter Boi", "Gold Digger", "Crazy in Love", "Ridin' Solo", "Single Ladies", "Dirty Little Secret", "Hot N Cold", "Stacy's Mom", "Fergalicious", "Bye, Bye, Bye", "Sugar, We're Goin Down", "1985", "Mr. Brightside", "Call Me Maybe", "Over My Head", "Wannabe", "Hall of Fame", "You Belong With Me", "Baby", "Year 3000", "Pokerface", "I'm a Believer", "Set Fire to the Rain", "Hey Soul Sister", "Everybody Talks", "Airplanes", "Baby Got Back", "I Wanna Dance with Somebody", "Hips Don't Lie", "Oops... I Did It Again", "I Want It That Way", "Super Bass", "California Girls", "Since You Been Gone", "How to Save a Life", "Want U Back", "Sweet Carolina", "Love the Way You Lie", "The Middle", "Ride with Me", "Potential Break Up Song", "Viva La Vida", "A Thousand Miles"]
    
    let movies = ["Titanic", "The Godfather", "Star Wars", "The Wizard of Oz", "Jaws", "Rocky", "Gone with the Wind", "Psycho", "The Terminator", "King Kong", "Jurassic Park", "Casablanca", "Back to the Future" ,"Raiders of the Lost Ark", "E.T.", "The Matrix", "Ferris Bueller's Day Off", "The Silence of the Lambs", "Citizen Kane", "High School Musical", "Cadet Kelly", "The Princess Bride", "The Shining", "Pulp Ficiton", "Top Gun", "Ghostbusters", "Forrest Gump", "Mission: Impossible", "Lady and the Tramp", "The Lion King", "Beauty and the Beast", "Saturday Night Fever", "Remember the Titans", "Avengers", "Harry Potter", "Caddyshack", "Dirty Dancing", "The Lord of the Rings", "Die Hard", "Toy Story", "Superman", "Singin' in the Rain", "A Christmas Story", "Rain Man", "The Sound of Music", "Edward Scissorhands", "Schindler's List", "Groundhog Day", "Mean Girls", "Blade Runner", "Poltergeist", "Scream", "I Know What You Did Last Summer", "Grease", "West Side Story", "Footloose", "It's a Wonderful Life", "The Sandlot", "Saving Private Ryan", "The Shawshank Redemption", "The Breakfast Club", "Sixteen Candles", "Planet of the Apes", "The Dark Knight", "10 Things I Hate About You", "The Exorcist", "Mary Poppins", "Rebel Without a Cause", "Apollo 13", "Willy Wonka and the Chocolate Factory", "Breakfast at Tiffany's", "Snow White and the Seven Dwarves", "Herbie Fully Loaded", "The Parent Trap", "Bambi", "Carrie", "Rudy", "Clueless", "Home Alone", "Pirates of the Caribbean", "V for Vendetta", "Finding Nemo", "Finding Dory", "Mrs. Doubtfire", "Peter Pan", "Jumanji", "Good Will Hunting", "Shrek", "Heathers", "Men in Black", "Deadpool", "The Truman Show"]
}

    let colors = ["Pink", "Purple", "Blue", "Yellow", "Orange", "Black", "Gray", "Green", "Absolute Zero", "Acajou", "Acid Green", "Aero", "Aero Blue", "African Violet", "Air Force Blue", "Air Superiority Blue", "Alabama Crimson", "Alabaster", "Alice Blue", "Alizarin Crimson", "Alloy Orange", "Almond", "Aluminum", "Amaranth", "Amazon", "Amber", "American blue", "American bronze", "American gold", "American green", "Amethyst", "Android green", "Anti-flash White", "Antique Brass", "Apple", "Apricot", "Aqua", "Aquamarine", "Arctic Lime", "Artichoke", "Arylide Yellow", "Ash Gray", "Aureolin", "Avocado", "Awesome", "Azure", "Azureish White", "Banana Yellow", "Banana Mania", "Baby Powder", "Barbie Pink", "Barn Red", "Battery Charged Blue", "Bittersweet Shimmer", "Black Shadows", "Blue-violet", "Brick Red", "Bright Yellow", "Bubble Gum", "Brunswick Green", "Cardinal", "Chestnut", "Cheese", "Coral", "Crimson", "Dandelion"]
let countries = ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Argentina", "Armenia", "Australia", "Austria", "Bahamas", "Bangladesh", "Barbados", "Belgium", "Belize", "Bolivia", "Bosnia", "Herzegovina", "Botswana", "Brazil", "Bulgaria", "Cambodia", "Canada", "Chad", "Chile", "China", "Colombia", "Costa Rica", "Croatia", "Cuba", "Czech Republic", "Denmark", "Domincan Republic", "Egypt", "Fiji", "Finland", "France", "Germany", "Greece", "Guatemala", "Haiti", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Kenya", "Libya", "Liechtenstein", "Luxembourg", "Madagascar", "Mexico", "Mongolia", "Montenegro", "Netherlands", "New Zealand", "North Korea", "Norway", "Pakistan", "Panama", "Peru", "Philippines", "Poland", "Portugal", "Russia", "Rwanda", "Serbia", "Sierra Leon", "Singapore", "Slovakia", "Slovenia", "South Africa", "South Korea", "Swaziland", "Sweden", "Switzerland", "Syria", "Tanzania", "Thailand", "Turkey", "Uganda", "Ukraine", "United Kingdom", "United Arab Emirates", "USA", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"]
let presidents = ["George Washington", "John Adams", "Thomas Jefferson", "John Quincy Adams", "Andrew Jackson", "Martin van Buren", "James K. Polk", "John Tyler", "James Madison", "James Monroe", "William Henry Harrison", "Zachary Taylor", "Millard Fillmore", "Franklin Pierce", "James Buchanan", "Abraham Lincoln", "Andrew Johnson", "Rutherford B. Hayes", "Ulysses S. Grant", "James A. Garfield", "Chester A. Arthur", "Grover Cleveland", "Benjamin Harrison", "William McKinley", "Theodore Roosevelt", "Calvin Coolidge", "Herbert Hoover", "Franklin D. Roosevelt", "William Howard Taft", "Woodrow Wilson", "Warren G. Harding", "Harry Truman", "Dwight Eisenhower", "John Kennedy", "Lyndon Johnson", "Richard Nixon", "Gerald Ford", "Jimmy Carter", "Ronald Reagan", "George Bush", "Bill Clinton", "George W. Bush", "Barack Obama"]
let authors = ["Agatha Christie", "Albert Camus", "Anne Frank", "Ernest Hemingway", "Ray Bradbury", "George R.R. Martin", "Gillian Flynn", "Stephen King", "J.K. Rowling", "Andrew Hart", "James Patterson", "Margaret Atwood", "Rick Riordan", "Kiera Cass", "JD Salinger", "Harper Lee", "Mark Twain", "Oscar Wilde", "Aldous Huxley", "Nathaniel Hawthorne", "William Faulkner", "Hilary Mantel", "Ronald Dahl", "Franz Kafka", "Neil Gaiman", "Virginia Woolf", "Anthony Burgess", "Maya Angelou", "Victor Hugo", "Ian McEwan", "HP Lovecraft", "Donna Tartt"]











